-- Sistem Informasi Akuntansi Perhitungan dan Pembayaran Royalty
-- PostgreSQL / Supabase
-- ERD: penulis (1) -> buku (N) -> royalty (N)

drop view if exists laporan_royalty;
drop table if exists royalty cascade;
drop table if exists buku cascade;
drop table if exists penulis cascade;

create table penulis (
    id_penulis bigint generated by default as identity primary key,
    nama_penulis varchar(150) not null,
    email varchar(150),
    no_hp varchar(20),
    created_at timestamptz default now()
);

create table buku (
    id_buku bigint generated by default as identity primary key,
    id_penulis bigint not null references penulis(id_penulis)
        on update cascade on delete restrict,
    judul_buku varchar(200) not null,
    harga_jual numeric(15,2) not null check (harga_jual >= 0),
    persentase_royalty numeric(5,2) not null
        check (persentase_royalty >= 0 and persentase_royalty <= 100),
    tanggal_terbit date,
    created_at timestamptz default now()
);

create table royalty (
    id_royalty bigint generated by default as identity primary key,
    id_buku bigint not null references buku(id_buku)
        on update cascade on delete restrict,
    periode date not null,
    jumlah_terjual integer not null check (jumlah_terjual >= 0),
    total_penjualan numeric(15,2) not null default 0 check (total_penjualan >= 0),
    nominal_royalty numeric(15,2) not null default 0 check (nominal_royalty >= 0),
    status_pembayaran varchar(20) not null default 'BELUM DIBAYAR'
        check (status_pembayaran in ('BELUM DIBAYAR','DIBAYAR')),
    tanggal_bayar date,
    created_at timestamptz default now(),
    unique (id_buku, periode)
);

create index idx_buku_penulis on buku(id_penulis);
create index idx_royalty_buku on royalty(id_buku);
create index idx_royalty_periode on royalty(periode);

create or replace view laporan_royalty as
select
    r.id_royalty,
    r.periode,
    p.id_penulis,
    p.nama_penulis,
    b.id_buku,
    b.judul_buku,
    b.harga_jual,
    b.persentase_royalty,
    r.jumlah_terjual,
    r.total_penjualan,
    r.nominal_royalty,
    r.status_pembayaran,
    r.tanggal_bayar
from royalty r
join buku b on r.id_buku = b.id_buku
join penulis p on b.id_penulis = p.id_penulis;

-- Data contoh (boleh dihapus)
insert into penulis (nama_penulis, email, no_hp) values
('Andrea Contoh', 'andrea@example.com', '081234567890'),
('Tere Contoh', 'tere@example.com', '081298765432');

insert into buku (id_penulis, judul_buku, harga_jual, persentase_royalty, tanggal_terbit) values
(1, 'Laut Senja', 50000, 10, '2026-01-15'),
(2, 'Langit Pagi', 75000, 12, '2026-02-20');

insert into royalty
(id_buku, periode, jumlah_terjual, total_penjualan, nominal_royalty, status_pembayaran)
values
(1, '2026-09-01', 100, 5000000, 500000, 'BELUM DIBAYAR'),
(2, '2026-09-01', 80, 6000000, 720000, 'DIBAYAR');
